language: generic

sudo : required
services:
  - docker

before_install:
  - docker build -t HannoJacobs/docker-react -f Dockerfile.dev . # github repo as the name, you can use anything as the name

script:
  - docker run -e CI=true HannoJacobs/docker-react npm run test

