version: '3'
services:
  web:
    build:
      context: . # put it in the current directory
      dockerfile: Dockerfile.dev # the new name.
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: . # put it in the current directory
      dockerfile: Dockerfile.dev # the new name.
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # make this execute the moment we run our tests